// <auto-generated />
using System;
using DekanPlus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DekanPlus.Infrastructure.Migrations
{
    [DbContext(typeof(DekanPlusDbContext))]
    partial class DekanPlusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DekanPlus.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "ix_departments_name_unique")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Direction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("qualification");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state_code");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StateCode" }, "ix_directions_state_code_unique")
                        .IsUnique();

                    b.ToTable("directions", (string)null);
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialty_id");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex(new[] { "Name" }, "ix_groups_name_unique")
                        .IsUnique();

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("direction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("qualification");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state_code");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectionId");

                    b.HasIndex(new[] { "StateCode" }, "ix_specialties_state_code_unique")
                        .IsUnique();

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_year");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("home_address");

                    b.Property<string>("RecordBookNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_book_number");

                    b.Property<string>("ResidenceAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("residence_address");

                    b.Property<string>("StudyForm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("study_form");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "RecordBookNumber" }, "ix_students_record_book_number_unique")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Group", b =>
                {
                    b.HasOne("DekanPlus.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Specialty", b =>
                {
                    b.HasOne("DekanPlus.Domain.Entities.Department", "Department")
                        .WithMany("Specialties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DekanPlus.Domain.Entities.Direction", "Direction")
                        .WithMany("Specialties")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Student", b =>
                {
                    b.HasOne("DekanPlus.Domain.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DekanPlus.Domain.ValueObjects.Expulsion", "Expulsion", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("expulsion_date");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("expulsion_reason");

                            b1.HasKey("StudentId");

                            b1.ToTable("students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("DekanPlus.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("middle_name");

                            b1.HasKey("StudentId");

                            b1.HasIndex(new[] { "FirstName" }, "ix_students_first_name_trgm");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex(new[] { "FirstName" }, "ix_students_first_name_trgm"), "gin");
                            NpgsqlIndexBuilderExtensions.HasOperators(b1.HasIndex(new[] { "FirstName" }, "ix_students_first_name_trgm"), new[] { "gin_trgm_ops" });

                            b1.HasIndex(new[] { "LastName" }, "ix_students_last_name_trgm");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex(new[] { "LastName" }, "ix_students_last_name_trgm"), "gin");
                            NpgsqlIndexBuilderExtensions.HasOperators(b1.HasIndex(new[] { "LastName" }, "ix_students_last_name_trgm"), new[] { "gin_trgm_ops" });

                            b1.ToTable("students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("Expulsion");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Department", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Direction", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DekanPlus.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
