<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>DekanPlus</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DekanPlus.Application\DekanPlus.Application.csproj" />
      <ProjectReference Include="..\DekanPlus.Domain\DekanPlus.Domain.csproj" />
      <ProjectReference Include="..\DekanPlus.Infrastructure\DekanPlus.Infrastructure.csproj" />
    </ItemGroup>

</Project>
